### PR TITLE
Added TypeScript definition

### PR DESCRIPTION
**Pull request by jjdbrinker**
I added the TypeScript definition for this package.

### CODE REVIEW

**Comment by tkellen** [comment]
Thanks @jjdbrinker! I no longer maintain this package so I have given you commit bit and publish rights on NPM. Please merge and release as you see fit :dancer:

**Comment by tkellen** [comment]
Actually, it looks like I can't find you on npm... would you mind sharing your username?

Cheers!

**Comment by jjdbrinker** [comment]
Hi Tyler,
Feel free to add me to the NPM package. I've updated my username so it reflex my github username. It's ~jjdbrinker now!

**Comment by tkellen** [comment]
Done!

**Comment by saostad** [comment]
Hi,
I tried to add the definition express-bearer-token but it can not find it!

`npm install -D @types/express-bearer-token`

**Comment by jjdbrinker** [comment]
I have to upgrade the NPM package, I'll do that over the weekend. Once that's done you won't need to install a separate typescript definition for this package.

**Pull request merged**
