### PR TITLE
update res.send api

### PR DESCRIPTION
**Pull request by madhums**

### CODE REVIEW

**Comment by tkellen** [comment]
Thanks for this @madhums!

I am not currently actively maintaining this project. Would you be amenable to my giving you commit access and publishing rights on npm? That would give you the ability to take this PR to completion.

**Comment by madhums** [comment]
@tkellen yes! would be great if you could do that! (also perhaps add me on npm as a collaborator so that I can release?) I am @madhums on npm

**Comment by tkellen** [comment]
Done and done!

**Comment by madhums** [comment]
Great! thanks a bunch!

**Pull request merged**
